apiVersion: v1
kind: Pod
metadata:
  name: privileged
  labels:
    app: privileged
spec:
  containers:
  - name: privileged-pod
    image: docker.io/nodyd/ana:latest
    imagePullPolicy: Always
    securityContext:
        privileged: true
  restartPolicy: OnFailure
