apiVersion: v1
kind: Pod
metadata:
  name: namespace-share
  labels:
    purpose: testing
spec:
  hostPID: true
  hostIPC: true
  hostUTS: true
  hostNetwork: true
  containers:
  - name: namespace-share
    image: docker.io/nodyd/ana:latest
    imagePullPolicy: Always
    securityContext:
      privileged: true
  restartPolicy: OnFailure
