apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello
  template:
    metadata:
      labels:
        run: hello
    spec:
      containers:
      - image: docker.ui/nodyd/hello:latest
        imagePullPolicy: Always
        name: hello
      - image: docker.io/nodyd/ssl-fwd:latest
        name: https
        imagePullPolicy: Always
        env:
        - name: DOMAIN
          value: hello
        - name: LISTEN
          value: "443"
        - name: SSL_DESTINATION
          value: "127.0.0.1:80"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: hello
  name: hello
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443
  selector:
    run: hello
