apiVersion: v1
kind: Pod
metadata:
  name: docker-sock
  labels:
    app: docker-sock
spec:
  containers:
  - name: docker-sock
    image: docker.io/nodyd/ana:latest
    imagePullPolicy: Always
    volumeMounts:
    - name: dockersock
      mountPath: "/var/run/docker.sock"
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
  restartPolicy: OnFailure
