apiVersion: v1
kind: Pod
metadata:
  name: docker-sock
  namespace: kube-system
spec:
  containers:
    - name: docker-sock
      image: nodyd/ana
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-sock
  volumes:
  - hostPath:
      path: /var/run/docker.sock
      type: File
    name: docker-sock

