apiVersion: v1
kind: Pod
metadata:
  name: privileged
spec:
  containers:
    - name: privileged
      image: nodyd/ana
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
